# ------------------------------------------------------------------------------
# This code was automatically generated by Boo.Lang.CodeDom v.0.9.2.3383.
# 
#      Changes to this file may cause incorrect behavior and will be lost if 
#      the code is regenerated.
# ------------------------------------------------------------------------------

namespace Pantheon.Test.Boo

/*describe_controller Monster:
    when Monster.DrinkCaffeine is sent
    then Monster.DrinkCaffeine should be received*/