# ------------------------------------------------------------------------------
# This code was automatically generated by Boo.Lang.CodeDom v.0.9.2.3383.
# 
#      Changes to this file may cause incorrect behavior and will be lost if 
#      the code is regenerated.
# ------------------------------------------------------------------------------

namespace Pantheon.Wat
import System


class MyClass():
    
    public def constructor():
        pass

